# Generated by Django 3.0.4 on 2020-03-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0001_initial'),
    ]

    operations = [
    ]
